name: Module Builder

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      # get part of the tag after the `v`
      - name: Extract tag version number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Echo tag output
        run: echo ${{ steps.get_version.outputs.version-without-v }}
      # Substitute the Manifest and Download URLs in the module.json
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: 'module.json'
        env:
          version: ${{steps.get_version.outputs.version-without-v}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{steps.get_version.outputs.version}}/rainbowroom.zip
     
      # Create a zip file with all files required by the module to add to the release
      - run: zip -r ./rainbowroom.zip module.json languages/ scripts/ templates/

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: './module.json, ./rainbowroom.zip'
          tag: ${{ steps.get-version.outputs.version }}
          body: ${{ github.event.release.body }}